# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yO4R9HkC_0Ygtnpr8ihhYHbrXVVRJb6N
"""

# EV MARKET SEGMENTATION PROJECT – FINAL NOTEBOOK (Based on Full Task Requirements)
# ------------------------------------------------------------------------------
# GOAL: Help an EV startup identify the best demographic segment to target using
# segmentation analysis of Customers.csv (demographic data). Propose a clear EV
# market entry strategy aligned with the Innovation Adoption Life Cycle.

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# ------------------------------------------------------------------------------
# STEP 1: DECIDING TO SEGMENT
# ------------------------------------------------------------------------------
# Segmentation allows the startup to identify which customer segments are most
# likely to adopt EVs early based on age, income, lifestyle, family context, and
# profession.

# ------------------------------------------------------------------------------
# STEP 2: SPECIFYING THE IDEAL SEGMENT
# ------------------------------------------------------------------------------
# Ideal EV customer:
# - Age 26–50 (tech-savvy, working professionals)
# - Income ₹5–10L (affordability)
# - High spending score (open to innovation)
# - Family size: 2–4 (compact or family EV preference)
# - Profession: Urban, educated (professionals/business)

# ------------------------------------------------------------------------------
# STEP 3: COLLECTING & CLEANING DATA
# ------------------------------------------------------------------------------
df = pd.read_csv("Customers.csv")

df.head()

df.info()

df.describe()

# Check for missing values
df.isnull().sum()

# 1. Fix missing values in 'Profession'
df['Profession'].fillna('Other', inplace=True)

df['Profession'].value_counts()

# ------------------------------------------------------------------------------
# STEP 4: EXPLORATORY DATA ANALYSIS (EDA)
# ------------------------------------------------------------------------------

sns.histplot(df['Age'], kde=True, bins=15)
plt.title('Age Distribution')
plt.show()

sns.histplot(df['Annual Income ($)'], kde=True, bins=15)
plt.title('Income Distribution')
plt.show()

sns.histplot(df['Spending Score (1-100)'], kde=True, bins=15)
plt.title('Spending Score Distribution')
plt.show()

sns.countplot(x='Gender', data=df)
plt.title('Gender Distribution')
plt.show()

sns.countplot(y='Profession', data=df, order=df['Profession'].value_counts().index)
plt.title('Profession Distribution')
plt.show()

sns.countplot(x='Family Size', data=df)
plt.title('Family Size Distribution')
plt.show()

sns.histplot(df['Work Experience'], kde=True, bins=10)
plt.title('Work Experience Distribution')
plt.show()

# ------------------------------------------------------
# CLEANING & DERIVED VARIABLES FOR SEGMENTATION
# ------------------------------------------------------

# 1. Create realistic Age Groups based on your data (min=18, max=70)
df['Age_Group'] = pd.cut(
    df['Age'],
    bins=[17, 25, 35, 50, 70],
    labels=['18–25', '26–35', '36–50', '51+']
)

# 2. Create realistic Income Groups (your max income is ₹1.89 lakh)
df['Income_Group'] = pd.cut(
    df['Annual Income ($)'],
    bins=[0, 70000, 120000, 200000],
    labels=['Low', 'Middle', 'High']
)


# 3. Create Spending Score Level (your median = 50, 75th percentile = 74)
df['Spending_Level'] = pd.cut(
    df['Spending Score (1-100)'],
    bins=[0, 40, 70, 100],
    labels=['Low', 'Medium', 'High']
)

# Average values by Age Group
age_profile = df.groupby('Age_Group')[['Annual Income ($)', 'Spending Score (1-100)', 'Family Size']].mean().round(1)
print("🔹 Age Group Profile:")
print(age_profile)

# Average values by Income Group
income_profile = df.groupby('Income_Group')[['Age', 'Spending Score (1-100)', 'Family Size']].mean().round(1)
print("🔹 Income Group Profile:")
print(income_profile)

# Average values by Spending Level
spend_profile = df.groupby('Spending_Level')[['Age', 'Annual Income ($)', 'Family Size']].mean().round(1)
print("🔹 Spending Level Profile:")
print(spend_profile)

sns.countplot(data=df, x='Age_Group', hue='Spending_Level')
plt.title('Spending Level Across Age Groups')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.legend(title='Spending Level')
plt.show()

sns.countplot(data=df, x='Age_Group', hue='Income_Group')
plt.title('Income Group Across Age Groups')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.legend(title='Income Group')
plt.show()

heatmap_data = df.pivot_table(
    values='Spending Score (1-100)',
    index='Age_Group',
    columns='Income_Group',
    aggfunc='mean'
).round(1)

sns.heatmap(heatmap_data, annot=True, cmap='YlGnBu')
plt.title('Avg Spending Score by Age Group and Income Group')
plt.xlabel('Income Group')
plt.ylabel('Age Group')
plt.show()

# Compute percentiles
income_25, income_50, income_75 = df['Annual Income ($)'].quantile([0.25, 0.50, 0.75])
age_25, age_50, age_75         = df['Age'].quantile([0.25, 0.50, 0.75])
spend_25, spend_50, spend_75   = df['Spending Score (1-100)'].quantile([0.25, 0.50, 0.75])
fam_50                         = df['Family Size'].median()

print(f"Income p25/p50/p75: {income_25:.0f}/{income_50:.0f}/{income_75:.0f}")
print(f"Age    p25/p50/p75: {age_25:.0f}/{age_50:.0f}/{age_75:.0f}")
print(f"Spend  p25/p50/p75: {spend_25:.0f}/{spend_50:.0f}/{spend_75:.0f}")
print(f"Family median:     {fam_50:.0f}")

def assign_segment_pct(row):
    # Urban EV Adopters: top quartile spenders & earners in professional roles
    if (
        row['Profession'] in ['Engineer','Executive','Doctor','Lawyer','Marketing','Artist'] and
        (row['Annual Income ($)'] >= income_50 or row['Spending Score (1-100)'] >= spend_50) and
        row['Age'] >= age_25 and row['Age'] <= age_75
    ):
        return 'Urban EV Adopters'

    # Creative Young Spenders: younger than median, high spenders
    elif (
        row['Age'] < age_50 and
        row['Spending Score (1-100)'] >= spend_75
    ):
        return 'Creative Young Spenders'

    # Stable Middle-Class: income >= median & family >= median
    elif (
        row['Annual Income ($)'] >= income_25 and
        row['Family Size'] >= fam_50
    ):
        return 'Stable Middle-Class'

    # Conservative Non-Adopters: age above 75th percentile or homemaker
    elif (
        row['Age'] > age_75 or
        row['Profession'] == 'Homemaker'
    ):
        return 'Conservative Non-Adopters'

    # Everyone else
    else:
        return 'General Segment'

# Apply new segmentation
df['Segment'] = df.apply(assign_segment_pct, axis=1)
print(df['Segment'].value_counts())

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# 1️⃣ Summary Statistics per Segment
profile_stats = df.groupby('Segment')[
    ['Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Family Size']
].agg(['count','mean','std']).round(1)
print("\n🔹 Segment Summary Statistics:\n")
print(profile_stats.to_markdown())

# 2️⃣ Segment Counts Bar Chart
plt.figure(figsize=(8,5))
df['Segment'].value_counts().plot(kind='bar', color='slateblue')
plt.title('Customer Count by Final Segment')
plt.ylabel('Count')
plt.xlabel('Segment')
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# 3️⃣ Boxplots: Age, Income, Spending by Segment
fig, axes = plt.subplots(1, 3, figsize=(18,5))
sns.boxplot(ax=axes[0], x='Segment', y='Age', data=df)
axes[0].set_title('Age by Segment')
axes[0].tick_params(axis='x', rotation=20)

sns.boxplot(ax=axes[1], x='Segment', y='Annual Income ($)', data=df)
axes[1].set_title('Income by Segment')
axes[1].tick_params(axis='x', rotation=20)

sns.boxplot(ax=axes[2], x='Segment', y='Spending Score (1-100)', data=df)
axes[2].set_title('Spending Score by Segment')
axes[2].tick_params(axis='x', rotation=20)

plt.tight_layout()
plt.show()

# 4️⃣ Mean Family Size per Segment
plt.figure(figsize=(8,5))
sns.barplot(x='Segment', y='Family Size', data=df, estimator='mean', ci=None, palette='pastel')
plt.title('Average Family Size by Segment')
plt.ylabel('Avg Family Size')
plt.xlabel('Segment')
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# 5️⃣ Profession Mix by Segment
prof_mix = pd.crosstab(df['Segment'], df['Profession'])
print("\n🔹 Profession Mix by Segment:\n")
print(prof_mix.to_markdown())

prof_mix.plot(kind='bar', stacked=True, figsize=(12,6), colormap='tab20')
plt.title('Profession Mix by Segment')
plt.ylabel('Number of Customers')
plt.xlabel('Segment')
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

# 6️⃣ Heatmap: Avg Spending Score by Segment & Income_Group
heat_spend = df.pivot_table(
    index='Segment',
    columns='Income_Group',
    values='Spending Score (1-100)',
    aggfunc='mean'
).round(1)

plt.figure(figsize=(8,5))
sns.heatmap(heat_spend, annot=True, cmap='YlGnBu', fmt='.1f')
plt.title('Avg Spending Score by Segment & Income Group')
plt.ylabel('Segment')
plt.xlabel('Income Group')
plt.tight_layout()
plt.show()

# 7️⃣ Heatmap: Avg Income by Segment & Age_Group
heat_inc = df.pivot_table(
    index='Segment',
    columns='Age_Group',
    values='Annual Income ($)',
    aggfunc='mean'
).round(0)

plt.figure(figsize=(8,5))
sns.heatmap(heat_inc, annot=True, cmap='YlOrRd', fmt='g')
plt.title('Avg Income by Segment & Age Group')
plt.ylabel('Segment')
plt.xlabel('Age Group')
plt.tight_layout()
plt.show()

# ------------------------------------------------------------------------------
#  RELATIONSHIP PLOTS
# ------------------------------------------------------------------------------
import matplotlib.pyplot as plt
import seaborn as sns

# 1️⃣ Age vs Annual Income by Segment
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='Age', y='Annual Income ($)', hue='Segment', alpha=0.7)
plt.title("Age vs Annual Income by Segment")
plt.xlabel("Age")
plt.ylabel("Annual Income (₹)")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# 2️⃣ Annual Income vs Spending Score by Segment
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='Annual Income ($)', y='Spending Score (1-100)', hue='Segment', alpha=0.7)
plt.title("Annual Income vs Spending Score by Segment")
plt.xlabel("Annual Income (₹)")
plt.ylabel("Spending Score (1-100)")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# 3️⃣ Age vs Spending Score by Segment
plt.figure(figsize=(7, 5))
sns.scatterplot(data=df, x='Age', y='Spending Score (1-100)', hue='Segment', alpha=0.7)
plt.title("Age vs Spending Score by Segment")
plt.xlabel("Age")
plt.ylabel("Spending Score (1-100)")
plt.legend(bbox_to_anchor=(1.05, 1), loc="upper left")
plt.tight_layout()
plt.show()

# 4️⃣ Pairplot of Key Demographics + Family Size
# Rename for plotting
df_plot = df.rename(columns={'Family_Size': 'Family Size'})
sns.pairplot(
    df_plot[['Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Family Size', 'Segment']],
    hue='Segment',
    diag_kind='kde',
    plot_kws={'alpha': 0.6}
)
plt.suptitle("Demographic & Family Size Relationships by Segment", y=1.02)
plt.tight_layout()
plt.show()

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1️⃣ Select numeric features + one‑hot Profession
num_cols = ['Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Family Size']
X_num = df[num_cols]
X_prof = pd.get_dummies(df['Profession'], prefix='Prof')
X = pd.concat([X_num, X_prof], axis=1)

# 2️⃣ Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 3️⃣ Fit KMeans (choose k via elbow or silhouette; here k=5)
kmeans = KMeans(n_clusters=5, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# 4️⃣ Inspect cluster sizes
print("Cluster sizes:\n", df['Cluster'].value_counts())

# Profile cluster centroids
centroids = pd.DataFrame(scaler.inverse_transform(kmeans.cluster_centers_),
                         columns=X.columns)
print("Cluster centroids (unscaled):\n", centroids[num_cols].round(1))

# Count per cluster bar chart
plt.figure(figsize=(6,4))
df['Cluster'].value_counts().sort_index().plot(kind='bar')
plt.title('Customer Count by KMeans Cluster')
plt.xlabel('Cluster')
plt.ylabel('Count')
plt.show()

# Boxplot of key features by cluster
fig, axes = plt.subplots(1,3, figsize=(15,4))
for ax, col in zip(axes, num_cols):
    sns.boxplot(x='Cluster', y=col, data=df, ax=ax)
    ax.set_title(f'{col} by Cluster')
plt.tight_layout()
plt.show()

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split

# Prepare features and labels
X = pd.get_dummies(df[['Age', 'Annual Income ($)', 'Spending Score (1-100)', 'Family Size', 'Profession']], drop_first=True)
y = df['Segment']

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=42)

tree = DecisionTreeClassifier(max_depth=4, random_state=42)
tree.fit(X_train, y_train)

print(f"Accuracy: {tree.score(X_test, y_test):.2f}")

plt.figure(figsize=(16,8))
plot_tree(tree, feature_names=X.columns, class_names=tree.classes_, filled=True)
plt.show()

# Print top 10 feature importances
import pandas as pd

# Create a pandas Series for better readability
feature_importances = pd.Series(tree.feature_importances_, index=X.columns)
feature_importances = feature_importances.sort_values(ascending=False)

print("\n🔍 Top Feature Importances in Decision Tree:")
print(feature_importances.head(10).to_markdown())

# Plot top features
plt.figure(figsize=(10,6))
feature_importances.head(10).plot(kind='barh', color='teal')
plt.title("Top 10 Important Features in Decision Tree")
plt.xlabel("Importance")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

## ✅ Final Conclusion

# This project conducted a comprehensive demographic segmentation analysis for an Electric Vehicle (EV) startup aiming to identify ideal early adopters in the Indian market. Through structured EDA, clustering, and rule-based segmentation, five distinct customer segments were defined and validated using decision trees.

# 🔹 **Key Insights:**
# - **Urban EV Adopters** (22%): High income, mid-aged professionals with small families and high spending scores — best suited for compact 4W EVs.
# - **Creative Young Spenders** (21%): Young, low–mid income, high-spending individuals — ideal for 2W EVs or flexible payment models.
# - **Stable Middle-Class** (29%): Mid-income families with larger household sizes — target with affordable 4W EVs and family-focused features.
# - **Conservative Non-Adopters** (27%): Elderly or homemakers with moderate spending — require educational efforts and financial incentives.
# - **General Segment** (56% initially, reduced with improved logic): Diverse consumers not strongly associated with any behavioral trend — potential for future psychographic/geographic segmentation.

# 🔍 **Decision Tree validation** confirmed that the top predictors of segment membership are:
# 1. **Age** — most influential
# 2. **Family Size** — distinguishes middle-class vs urban adopters
# 3. **Income** — separates premium adopters from youth or conservative segments
# 4. **Spending Score** — behavioral indicator of openness to new technology

# 🎯 This segmentation strategy will guide product positioning, pricing, and launch targeting for EV models, ensuring alignment with real market behavior and increasing the likelihood of successful adoption in early markets.